"""create v0.1 core domain tables

Revision ID: e0252e2b8984
Revises: 
Create Date: 2026-09-24 17:27:28.043083

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0252e2b8984'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_points',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_points.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_points_parent_id', 'knowledge_points', ['parent_id'], unique=False)
    op.create_table('questions',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='ck_questions_status'),
    sa.CheckConstraint("type IN ('single_choice')", name='ck_questions_type'),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name='ck_questions_difficulty_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_difficulty', 'questions', ['difficulty'], unique=False)
    op.create_index('ix_questions_status', 'questions', ['status'], unique=False)
    op.create_table('users',
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openid')
    )
    op.create_table('question_knowledge_points',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_point_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'knowledge_point_id')
    )
    op.create_table('question_options',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=8), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'key', name='uq_question_options_question_key')
    )
    op.create_index(op.f('ix_question_options_question_id'), 'question_options', ['question_id'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('total_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("mode IN ('daily', 'practice', 'review')", name='ck_quiz_sessions_mode'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quiz_sessions_user_id', 'quiz_sessions', ['user_id'], unique=False)
    op.create_table('review_items',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_point_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('review_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'completed')", name='ck_review_items_status'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_items_scheduled_at', 'review_items', ['scheduled_at'], unique=False)
    op.create_index('ix_review_items_status', 'review_items', ['status'], unique=False)
    op.create_index('ix_review_items_user_id', 'review_items', ['user_id'], unique=False)
    op.create_table('user_knowledge_stats',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_point_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('correct_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wrong_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mastery_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('mastery_score >= 0.0 AND mastery_score <= 1.0', name='ck_user_knowledge_stats_mastery_range'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'knowledge_point_id', name='uq_user_knowledge_stats_user_kp')
    )
    op.create_index('ix_user_knowledge_stats_knowledge_point_id', 'user_knowledge_stats', ['knowledge_point_id'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent_ms', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quiz_answers_answered_at', 'quiz_answers', ['answered_at'], unique=False)
    op.create_index('ix_quiz_answers_question_id', 'quiz_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_session_id'), 'quiz_answers', ['session_id'], unique=False)
    op.create_index('ix_quiz_answers_user_id', 'quiz_answers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quiz_answers_user_id', table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_session_id'), table_name='quiz_answers')
    op.drop_index('ix_quiz_answers_question_id', table_name='quiz_answers')
    op.drop_index('ix_quiz_answers_answered_at', table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_index('ix_user_knowledge_stats_knowledge_point_id', table_name='user_knowledge_stats')
    op.drop_table('user_knowledge_stats')
    op.drop_index('ix_review_items_user_id', table_name='review_items')
    op.drop_index('ix_review_items_status', table_name='review_items')
    op.drop_index('ix_review_items_scheduled_at', table_name='review_items')
    op.drop_table('review_items')
    op.drop_index('ix_quiz_sessions_user_id', table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index(op.f('ix_question_options_question_id'), table_name='question_options')
    op.drop_table('question_options')
    op.drop_table('question_knowledge_points')
    op.drop_table('users')
    op.drop_index('ix_questions_status', table_name='questions')
    op.drop_index('ix_questions_difficulty', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_knowledge_points_parent_id', table_name='knowledge_points')
    op.drop_table('knowledge_points')
    # ### end Alembic commands ###
